#+html_head: <link rel="stylesheet" href="../doc-style.css" type="text/css"/>
#+title: Tutorial #2: Objects and Structures 
#+options: num:nil toc:nil

[[file:programmer-1.org][Prev]]  [[file:../index.org][Up]]  [[file:programmer-3.org][Next]]

* The Relic Object Philosophy
In a traditional object-oriented language, objects perform a variety of
functions - they can encapsulate state, represent abstractions, allow code reuse
via inheritance and so on. In Relic, the design of objects is singularly focused
on encapsulating state. 


* A Simple Object
We will start with a simple object - a square. This square has a single /slot/,
called length, which is initialized to 4.

We further define two messages that the object can receive (methods).
In response to the =;length= message, we simply return the length of a side of
the square. In response to the =;area= message, we calculate area from the
length message.

#+begin_src relic
(def my-square object [(length 4)]
  (;length -> length)
  (;area -> (* length length)))
#+end_src

We are now able to invoke these messages on our square:

#+begin_src relic
(;length my-square) ;; => 4
(;area my-square)   ;; => 16
#+end_src

#+begin_src relic
(def square fn (length) object [(length 4)]
  (;length -> length)
  (;area -> * length length))
#+end_src

* Slots
Let's move on to a more complex example: suppose that we want to be able to set
the length/area of our square. Suppose further that we want to cache the area so
that we don't need to recompute it each time the =;area= message is sent. We can
use the =sets= function to /set/ the value of a /slot/.

#+begin_src relic
(def mut-square fn (initial-length) object
    [(length initial-length)
     (area (* initial-length initial-length))]

  (;length -> length)
  (;set-length new-length -> seq
    (sets length new-length)
    (sets area (* length length)))

  (;area -> area)
  (;set-area new-length -> seq
    (sets area new-area)
    (sets length (sqrt area))))
#+end_src


#+begin_src relic
(def my-square mut-square 3)
(;area my-square) ;; => 9

(;set-area my-square 16)
(;length my-square) ;; => 4
#+end_src
