#+html_head: <link rel="stylesheet" href="../doc-style.css" type="text/css"/>
#+title: Tutorial #2: Projects and Structures 
#+options: num:nil toc:nil

[[file:programmer-1.org][Prev]]  [[file:../index.org][Up]]  [[file:programmer-3.org][Next]]

* Current Directory
Here, we will focus on adding some simple features to our shell. First up, it is
common for a shell to print the name of the current directory before the prompt.
In Relic, we can access this string with =get-current-directory=, which will
return a (freshly allocated) string with the name of the current directory. As
with =read-line=, we will need to free this memory later. Let's replace our call
to =write-string= with a =prompt= function which will print the prompt for the
user.

#+begin_src relic
(def prompt proc [] seq
  [let cwd (platform.filesystem.get-current-directory)]
  (write-line cwd)
  (data.string.delete cwd)
  (write-string "> "))
#+end_src

Inside our main function, we then can rewrite the loop.
#+begin_src relic
  (loop 
    (prompt)
    [while (iter (read-line))])
#+end_src

Before moving on, now is a good time to start thinking about *imports* referring
to the =get-current-directory= function by the fill import path is a bit
unwieldy, so we can /import/ the filesystem module, meaning that we can simply
refer to =filesystem.get-current-directory=. 

#+begin_src relic
(import platform.filesystem)

;;....
 
(def prompt proc [] seq
  [let cwd (filesystem.get-current-directory)]
  (write-line cwd)
  (data.string.delete cwd)
  (write-string "> "))
#+end_src

* Commands
Of cource, once we display the current directory, we will want a way to change it.
This can be done in relic using =set-current-directory=, but before we can do
/that/, we first need to provide our shell with the ability to recognize
different commands, beyond just 'exit'.

The natural next step then is to separate our input string on spaces, so let's
start by importing some functions that will be useful later.

#+begin_src relic
(import
 platform.filesystem
 platform.memory

 (data.pointer :only (get set local))
 (data.list :only (mk-list push elt))
 (data.string :only (subview nth-byte)))
#+end_src

Our algorithm will run as follows:
- Initialize the compoents (list of strings we want to return) to an empty list
- Initialize the start of the *current word* to the start of the string

Then, we will loop over each character in the string, and:
- If current character is a space, do to things:
  - Add a new word starting at our most recent word start, and ending just
    before the current character. 
  - Reset the start of the current word to the character after the current one

Note that the last character may NOT be a space, so once our loop finishes, we
will need to act as if there is an extra character that /is/ a space at the end
of the loop, to ensure the last word gets pushed on.

This algorithm is not perfect, and handles, e.g. double spaces less than
ideally, however, it is nice and simple, and should be more than enough for our
purposes.

We will start with our initialization. In Relic, the only way to get mutable
values by mutating memory explicitly, i.e. via pointers. We can use the =local=
function that we imported from the =pointer= module to create a pointer using
local (i.e. on-stack) memory. Note that you should *never* return a local
pointer from a procedure, as local (stack) memory is invalid once the procedure
returns.

We can initialize =start= with 0, and we want to initialize our list with 0
elements, but with space reserved for 8. 8 has been chosen as it will be enough
for most cases without being excessive, as lists will automatically grow if we
exceed their capacity.

#+begin_src relic
(def split-on proc [str delimiter] seq
  [let! start (local 0)]
  [let! components (local (list.mk-list 0 8))]

  ;; Rest of the function goes here...
  )
#+end_src

The body of the loop is relatively easy to fill out, and we will make use of a
new piece of syntax and some new functions. The =when= conditional is like if,
but has no =:false= branch, as it is assumed implicitly return the value
=:unit=. Additionally, like =proc= and =def=, it performs auto parenthesization
after the condition.

Our new functions are =push= which will add a value to the end of our list, and
=subview=, which is like =substring=, but does not allocate any memory, it
simply provides a substring which views the original memory. This will make
cleanup easier later. The arguments to =subview= are the start and end position
of the substing, together with the original string we want to take the substring
of.

#+begin_src relic
(def split-on proc [str delimiter] seq
  [let! start (local 0)]
  [let! components (local (list.mk-list 0 8))]

  (loop [for i from 0 below str.memsize]
    (when (= (nth-byte i str) delimiter) seq

      ;; Push the subcommant 
      (push (subview (get start) i str) components)
      ;; Set the start of the next womd to the character after the current one
      (set start (+ i 1))))
  ;; Rest of the function goes here...
  )
#+end_src

To finish the function, we will want to do the final subview push, to treat the
character /after/ the last character as a space, then we will want to return the
value in the components pointer, which we can do with the =get= function.

#+begin_src relic
(def split-on proc [str delimiter] seq
  [let! start (local 0)]
  [let! components (local (list.mk-list 0 8))]

  (loop [for i from 0 below str.memsize]
    (when (= (nth-byte i str) delimiter) seq

      ;; Push the subcommant 
      (push (subview (get start) i str) components)
      ;; Set the start of the next word to the character after the current one
      (set start (+ i 1))))

  (push (subview (get start) str.memsize str) components)
  (get components))
#+end_src

Now that we have our =split-on= function, we can re-write our =iter= function,
by getting the commands from the input line, then printing out each, which will
be a useful diagnostic to see if our procedure works correctly. To write a
character literal in Relic, we use #<char>, so =#a= is the character literal for
a. Note that in Relic, there is no difference between a character and a
function, so =#a= is the same as the number literal =97=. For some 'special'
characters, we refer to them by name, so space is =#space=. 

Once we are done with them, we can free the memory associated with the
underlying list with =memory.free=.

#+begin_src relic
(def iter proc [str] seq
  [let! commands (split-on str #space)]

  (loop [for i from 0 below commands.len]
    (write-line (elt i commands)))

  [let! should-exit (if (= str "exit") :false :true)]
  (memory.free commands.data)
  (string.delete str)
  should-exit)
#+end_src

* Branching Conditionals

* Allocators
While we have managed to add some basic functionality to our shell, remembering
when to free memory is becoming a bit of a pain. Fortunately, we have a
solution: allocators. 

* Project
