#+html_head: <link rel="stylesheet" href="../doc-style.css" type="text/css"/>
#+title: Tutorial #0: Hi, Relic!
#+options: num:nil toc:nil


Prev [[file:../index.org][Up]] [[file:programmer-1.org][Next]]

* IMPORTANT
At current, this tutorial is very much a work in progress. For a much better
introduction to the basics of relic, it is recommended you chedkout the readme
of the [[https://github.com/rationalis-petra/pico][pico compiler]]. 

* About this Tutorial
This tutorial is intended to be an introduction to the for developers who have
already programmed in at least one standard "popular" language such as python,
C/C++, Java etc. No prior experience is assumed with the many "weird" languages
Relic draws from (lisp, forth, prolog etc.).


* Intro & Installation
Pico (the Relic compiler) is available on Windows or Linux as an AMD64
executable. To install, download the [[https://github.com/rationalis-petra/pico/releases/latest][latest release]], unzip the file, navigate to
the folder corresponding to your OS and run the installer executable.

Now, you should be able to start the compiler by running either =relic= or
=pico= from a command-line. =relic help= will  

* Read, Eval, Print, Loop!
To begin with, this first tutorial will use the REPL (Read-Eval-Print-Loop). You
can get here by running =relic repl=, although I recommend running in
interactive mode with =relic repl -i=. Once the REPL is running, you can type in
Relic expressions and hit enter to have them evaluated. We'll start with a
simple one: writing to the terminal.

#+begin_src relic
(write-line "Hello, World!")
#+end_src

After running, you will now see "Hello, World!" printed on a new line,
followed by the term =:unit=. This is because after running, the =write-line=
function returns the value =:unit=, which the repl then prints to the command
line. Nice!

You will likely also have noticed that the function call uses an unusuan
syntax - in Relic, instead of writing function calls as, e.g. =add(2, 3)=, we
write them =(add 2 3)=. This applies to operators also - instead of =2 + 3= we
write =(+ 2 3)=. This style can be confusing at first, but it also empowers a
feature of Relic we will meet later: metaprogramming.

With this knowledge in hand, we can try evaluating some other expressions, e.g. 

#+begin_src relic
(* 2 3)
(- 3 (* 4 5))
(< 2 3)
#+end_src

Try some of your own!

** Definitions
#+begin_src relic
(def your-name "Bob")
#+end_src

#+begin_src relic
(write-line (append "Hi, " your-name))
#+end_src


** Conditionals

#+begin_src relic
(if (< 2 3)
  (write-line "two is less than three")
  (write-line "three is less than two??"))
#+end_src

