#+html_head: <link rel="stylesheet" href="../doc-style.css" type="text/css"/>
#+title: Tutorial #0: Hi, Relic!
#+options: num:nil toc:nil


Prev [[file:../index.org][Up]] [[file:programmer-1.org][Next]]

* IMPORTANT
At current, this tutorial is very much a work in progress. For a much better
introduction to the basics of relic, it is recommended you chedkout the readme
of the [[https://github.com/rationalis-petra/pico][pico compiler]]. 

* About this Tutorial
This tutorial is intended to be an introduction to the for developers who have
already programmed in at least one standard "popular" language such as python,
C/C++, Java etc. No prior experience is assumed with the many "weird" languages
Relic draws from (lisp, forth, prolog etc.).


* Getting Started

Relic is powered by Pico, the Relic compiler. It is available for Windows and
Linux as an AMD64 executable. To install, download the [[https://github.com/rationalis-petra/pico/releases/latest][latest release]], unzip the
archive, navigate to your operating system's folder, and execute the appropriate
installer.

Once installed, you can start the compiler by running either =relic= or =pico=
from the command line. For general assistance, run =relic help= to see available
commands and options. 

* Diving into the REPL

This tutorial begins with the REPL, Relic's Read-Eval-Print Loop environment.
Launch the REPL by running =relic repl= from the command line. For an enhanced
experience, add the =-i= flag to run in interactive mode: =relic repl -i=,
although be aware that this is currently experimental and you may encounter bugs.
Inside the REPL, you can evaluate Relic expressions line by line. Let's start
with some simple arithmetic. If you type =(+ 11 7)= and hit Enter, you should
see the following.

#+begin_src relic
user > (+ 11 7)
18
#+end_src

This is because Relic will evaluate the 

After running, you will now see "Hello, World!" printed on a new line,
followed by the term =:unit=. This is because after running, the =write-line=
function returns the value =:unit=, which the repl then prints to the command
line. Nice!

Relic uses a unique syntax for function calls. Instead of the standard
=add(2, 3)=, functions in Relic are written as =(add 2 3)=. This prefix style
even applies to operators. For example, instead of =2 + 3=, you would write
=(+ 2 3)=. While this syntax may seem unusual initially, it integrates
seamlessly with Relic's advanced features like metaprogramming, which we'll
explore later.

With this knowledge in hand, we can try evaluating some other expressions, e.g. 

#+begin_src relic
(* 2 3)
(- 3 (* 4 5))
(< 2 3)
#+end_src

Try some of your own!

** Defining Values and Writing Functions

Relic uses the `def` term to define values. For example:

#+begin_src relic
(def x 10)  ;; Defines x as 10.
#+end_src

You can also use `proc` to define functions. Functions in Relic take arguments
and return results. For instance: 

#+begin_src relic
(def add-one
  (proc [(x I64)]
    (+ x 1)))
#+end_src

Here, we define a function called `add-one` that increments a number by one.

* Writing Your First Program

Now, let's put everything together to write a simple program:

#+begin_src relic
;; Define a main function
(def main
  (proc []
    (write-line "Hello, World!")))

;; Call the main function to execute
(main)
#+end_src

Save this program in a file called `hello-world.rl` and run it with the Relic
compiler:

#+begin_src bash
relic hello-world.rl
#+end_src

This will print:

#+begin_example
Hello, World!
#+end_example
