#+html_head: <link rel="stylesheet" href="../doc-style.css" type="text/css"/>
#+title: Tutorial #3: Administrative Duties
#+options: num:nil toc:nil

[[file:programmer-2.org][Prev]]  [[file:../index.org][Up]]  [[file:programmer-4.org][Next]]
 
* Next Steps
Thus far, the primary focus of these tutorials has been on introducing new
features to our shell. We will now take a step back and do some housekeeping on
this project, divided into three distinct phases:
- Making use of the *atlas* build system
- Swapping our shell to use an arena allocator based design
- Handling errors correctly.

* Modules and Atlas
We will start our cleanup with the files themselves, by refactoring our project
to be modular, and make use of the built-in build system for Relic: *atlas*.

Previously, the shell program was just a single file: =shell.rl=. Using *atlas*,
we will update it to have the following structure:

#+begin_export ascii
shell
├ atlas-project 
└ src 
  ├ atlas
  ├ main.rl
  └ commands.rl
#+end_export

You can start by just moving the =shell.rl= to where =main.rl= is in this file
structure; we will walk through the purporse and contents of each of these files
later. We will start with the first file, =atlas-project=. As the name implies,
there is only one of these files per project, and it should be placed at the
root of the project. It specifies:
- What version of atlas to use.
- What dependenc(y/ies) on other packages it has.

At the moment, there is only one version of atlas (0.0.1), and we have only one
dependency, =base=, which is relic's name for the standard library.

#+begin_src atlas
(lang atlas 0.0.1)

(package (name shell)
  (dependencies base))
#+end_src

The next file is the =atlas= file. Generally, you will want one of these per
subdirectory in your =src=. Note that the name =src= is not special, when
running atlas, once it detects an =atlas-project= file, it will recursively
search all subdirectories for file with the name =atlas= and assume that they
describe the build. In our case, we need only one.

The two primary clauses that we use inside an atlas file are the /executable/
and /library/ clauses. Both are effectively identical, except that the
executable clause also requires an /entry-point/. The general components of a
library/executable is as follows

- file :: The file containing the executable/library. *MUST* be a module file
  (more on that later). Note that ".rl" is appended automatically to the filenames.
- dependencies :: Optional. The libraries that the library/executable depends
  on.
- name :: The name of the library/executable. Used in dependency lists, and
  when running programs from the terminal.
- entry-point :: Executable only. Must be a name of a function defined in the
  module, and is the function that is called at the start of execution. When the
  entry-point function returns, the program exits/finishes.

#+begin_src atlas
(executable
  (name shell)

  (file "main")
  (entry-point main)

  (dependencies commands))

(library 
  (name commands)
  (file "commands"))
#+end_src

Now that we have the project structure set up, the next step is to rewrite our
single =shell.rl= into the two files, =commands.rl= and =main.rl=. We will start
with =commands.rl=. Start by copying the three 'command functions

#+begin_src relic
(def unrecognized proc [cmd] seq
  (write-string "Unrecognized command: ")
  (write-line cmd))

(def echo proc [args] seq
  (loop [for i from 1 below args.len]
    (write-string (elt i args))
    (write-string " "))
  (write-string "\n"))

(def cd proc [args] labels
  (seq
    (when (u64.< args.len 1)
      (go-to early-exit "error: cd requires an argument; none was provided"))
    (when (u64.> args.len 2)
      (go-to early-exit "error: cd requires exactly one argument; too many were provided"))

    (write-string "changing dir to: ")
    (write-line (elt 1 args))
    (fs.set-current-directory (elt 1 args)))

  [early-exit [reason]
   (write-line reason)])
#+end_src

To convert from a module file to a script file is relatively easy: all we need
to do is add a =modlue= header at the top of the file. The module header will be
where we coalesce all imports to the module, as well as specifying what the
module exports.

Looking at the code, we can cut down out the original for =shell.rl= and depend
only on
- The filesystem module (for cd)
- The =elt= list method

Our module header thus looks like:

#+begin_src relic
(module commands
  (import
    (platform.filesystem :as fs)

    (data.list :only (elt)))
  (export unrecognized echo cd))
#+end_src

However, if we try to load the module as-is, we would find that we quickly run
into errors. This is because when running a script, a bunch of modules are
already imported for us. In particular:
- Core contains 
- Extra contains macros (more on these later) that add 'nice to haves' int the
  language, such as =loop= and =when=.
- Num contains a module for each primitive numeric type, i.e. =u8=, =u64=,
  =f32=, etc. We use this for comparison (=u64.<=).

In our case, we will be a but lazy and import all sympols from these modules.
So, our full module header becomes:

#+begin_src relic
(module commands
  (import
   (core :all)
   (extra :all)
   (num :all)

   (platform.filesystem :as fs)
   (platform.terminal :all)

   (data.list :only (elt)))

 (export :all))
#+end_src

Our main (shell) module will be similar: copy to it all functions *except* the
three 'command' functions. The only export is our entry-point (=main=). Remember
to remove the call to =main= at the end of the file, otherwise our shell will
run twice!.

We will also need some more imports in our header: we want the original set of
imports from =shell=, plus the onse we added to =commands=, together with the
following:

- *data* :: Contains modules for data-structures like =list= and =string=
- *abs.equality* :: Contains the =Eq= trait and instances. Traits and instances
  will be covered later, but for now all you need to know is that it lets us use
  the ~=~ function with different types, so ~(= 3 4)~ and ~(= "hello" "hello")~
  both work.
- *abs.numeric* :: Contains the =Num= trait and instances, which let us use =+=,
  =-=, etc. in a generic way.

The full header for =main.rl= is thus:

#+begin_src relic
(module shell
  (import
   (core :all)
   (extra :all)
   (data :all)
   (num :all)
   (abs.equality :all)
   (abs.numeric :all)

   platform.memory
   (platform.filesystem :as fs)
   (platform.terminal :all)

   (data.pointer :only (get set local))
   (data.list :only (mk-list push elt))
   (data.string :only (subview nth-byte))

   (commands :all))
  (export main))
#+end_src

Now that all of these files have been written, using your command line, navigate
to the same folder that =atlas-project= is in and type =atlas run shell=.
Assuming that you haven't made any mistakes, you should see your shell prompt.

*Note*: while it is not /yet/ implemented, support for building executable files
is planned. Once this feature drops, =altas build shell= will produce a ~*.exe~
file from your shell program.

* Allocators

* Enums and Error Handling
