#+html_head: <link rel="stylesheet" href="../../../doc-style.css" type="text/css"/>
#+title: Data.String
#+options: num:nil toc:nil

[[file:../index.org][up]]

* Types 
+ String : Type ::
  The String type stores string data as a struct containing of a block of UTF-8
  bytes with  and a length. Strings do NOT have a null-terminator, which means
  that care must be taken when intefacing with C libraries.

* Functions 
+ nth-byte : Proc [U64 String] U8 ::
  Get the nth byte of the underlying memory of the string

+ from-ascii : Proc [(List U8)] String ::
  Converts a list of ASCII bytes into a string, allocating new memory for the
  string bytes. Note that the bytes are assumed to NOT be null-terminated, so a
  null-terminator is pushed onto the end of the string.

+ delete : Proc [String] Unit ::
  Free the underlying memory of the string, assuming it is allocated with =current-allocator=.

+ = : Proc [String String] Bool ::
  Return true if the two strings are equal, and false otherwise.

+ != : Proc [String String] Bool ::
  Return true if the two strings are *not* equal, and false otherwise.
