#+html_head: <link rel="stylesheet" href="../doc-style.css" type="text/css"/>
#+title: Discussion: Memory and Mutability
#+options: num:nil toc:nil

* Relic, Memory and Mutability
Two fundamental divides in the design of programming languages are how they
handle memory and mutation. 


* In The Beginning: C




* And Then: Garbage Collection

* An Alterantive: Borrow Checking

** Criticisms of Borrow Checking
- Borrow-checking encourages programmers to focus more on satisfying the borrow
  checker rather than managing memory. This can lead to architectures which
  avoid sharing data by making use of many deep copies, and which constantly
  allocate and deallocate data for each function-call. This is safe, but
  sacrifices performance (an advantage manual memory management supposed
- Borrow-checking encourages design patterns where programmers effectively
  re-implement manual memory, e.g. by storing indexes into large arrays
  instead of pointers. These can have the same issues (use-after free,
  double-free, leaks etc.) but the extra indirection hurts the ability of, e.g.
  sanitisation tools to detect these issues. While this is still superior from a
  security point-of-view, it can still cause similar issues (crashes/unusual
  bugs due to unintentional memory re-use).
- The borrow checker adds significant mental overhead, 


Interoperating Safe and Unsafe Rust can make code more bug-prone than other
unsafe languages, particularly modern ones such as zig, odin etc. This is
because the compiler decides where to place allocations and frees based on a
number of aliasing and borrowing rules, which must be followed in unsafe code.
This can make the contracts of lifetimes etc. between unsafe and safe functions
significany more complex than a language where the developer has control of all
memory allocation

* Relic's Approach
When analysing the design of the memory management system, we must consider
the three design goals of relic:
1. Relic should be expose the capabilities of the host platform. In particular,
   to unlock both the full performance potential of the host device and the
   ability to write certain programs (such as drivers or language runtimes with garbage
   collectors), manual memory management and mutation are a must.
2. Relic should enable a broad range of styles. This means that we should offer
   abstractions that let a programmer opt-in to automatic memory management.
3. Relic should be aware of and freindly to tooling. This means that it should be
   easy to write bug-detection software (such as sanitisers) which can track
   memory and detect bugs at runtime.


** Embracing Unsafety: the Address
Having determined (from point 1) that we require manual memory management, we
look at other languages which offer it and find that they have pointers.
Pointers, are simply a thin wrapper over the concept of an address, i.e. a
number which points to a location in memory. So, Relic has an address type
together with two fundamental operations: load and store.

#+begin_src relic
(ann Address Type)

(ann load All [A] Proc [Address] A)
(ann store All [A] Proc [Address A] Unit)
#+end_src

It may seem odd, coming from other languages, to have load and store be
functions, but doing the advantage that tools or tests may substitute the
implementation of load and store for one which perform certain diagnostics or
checks, such as whether the address is NULL or whether it lies within an 
expected region of memory. Additionally, when not testing, the compiler can
avoid paying a performance overhead by simply inlining the calls, leaving us
with the same machine code that could have been generated by, for example, a C
program.

Assuming that we have access to a 'malloc' and 'free' from the platform, we now
have a nearly complete set of capabilities. While it may appear that this design
will face issues with type-safety, as having an untyped address may make it easy
to mix-up what type is supposed to be stored at what address, we can actually
reproduce a Pointer API with a module. The code below demonstrates a module
which implements a simple API. While it does not handle error conditions such as
an allocation failure, it does completely prevent uninitialized memory issues.
Additionally, one may in principle similarly add some checks to the pointer
funcitons when running in debug/test mode.

#+begin_src relic
(module pointer
 (import (core :all))
 (export :all))

(def Pointer Family [A] Opaque Address)

(ann get All [A] Proc [(Pointer A)] A)
(def get all [A] proc [ptr] (load {A} (out-of (Pointer A) ptr)))

(ann set All [A] Proc [(Pointer A) A] Unit)
(def get all [A] proc [val ptr] (store {A} (out-of (Pointer A) ptr) val))


(ann new All [A] Proc [A] (Pointer A))
(def new all [A] proc [ptr] (load {A} (out-of (Pointer A) ptr)))

(ann delete All [A] Proc [(Pointer A)] Unit)
(def delete all [A] proc [ptr] (free (out-of (Pointer A))))
#+end_src

You may note that there are some things the above API cannot handle, however,
such as NULL pointers or the ability to index values in a contiguous array of
memory. We could add a specific =NULL= address, and the ability to add/subbtrat numbers
to/from addresses, but all of these capabilities can be achieved with a much
simpler API - a pair of functions which can wrap a number as an address, or
unwrap an address to get a number. Given that addresses are implemented as
numbers, both of these 'functions' are effectively no-ops which serve primarily
to perform type-casting.

#+begin_src relic
(address-to-num :: Proc [Address] U64)
(num-to-address :: Proc [U64] Address)
#+end_src

Thus, with one core type and 4 functions, we can replicate all the needed
functions of pointers in Relic. This gives us a final pointer/memory API with
only 1 type and 5 functions.  

#+begin_src relic
(Address Type)

(ann load All [A] Proc [Address] A)
(ann store All [A] Proc [Address A] Unit)
(ann address-to-num Proc [Address] U64)
(ann num-to-address Proc [U64] Address)
#+end_src

*** What was left Behind?
TODO: consider the following

- volatile addresses?
- memory on the stack? 
  - resets
- Alignment?


* Managed Memory
Desirable qualities of a safe memeory system:
- Ergonomically create mutable vaues on the stack.
- Automatically handle alloc/free
- ?? Borrow-Check ??

Ref 

#+begin_src relic
#+end_src

TODO: look into the borrow checker/lifetimes in rust.
Consider: borrow-checkers make things too complex?




